src/TabPane.jsx

fix tabPanel prefixCls

---

README.md
src/Nav.jsx
src/Tabs.jsx

inkBarstyle & barStyle

---

src/TabPane.jsx

ref: https://github.com/ant-design/ant-design/issues/3080

fix: should support TabPane[className]

---

src/TabBarMixin.js

https://github.com/ant-design/ant-design-mobile/issues/296

feat: tabbar supports className prop

---

package.json
src/utils.js

- close https://github.com/ant-design/ant-design/issues/3750

getActiveIndex use React.Children.map instead of Array.prototype.forEach

---

assets/index/common.less
examples/activeKey.js
src/TabContent.js
src/utils.js

Close: https://github.com/ant-design/ant-design/issues/3943

feat: add animatedWithMargin to work with positon fixed

---

assets/index/common.less

change content width

---

assets/index/bottom.less
assets/index/left.less
assets/index/right.less
assets/index/top.less
examples/swipeInkTabBar.html
examples/swipeInkTabBar.js
package.json
src/SwipeableInkTabBar.js
src/SwipeableTabBar.js
src/SwipeableTabBarMixin.js

close https://github.com/ant-design/ant-design-mobile/issues/394
ref: https://github.com/ant-design/ant-design-mobile/pull/882
ref: `gitlab/react-ui/ant-mobile/issues/404`

[WIP] feat: add swipeableTabBar for antd-mobile

---

README.md
src/ScrollableTabBarMixin.js
tests/__snapshots__/index.spec.js.snap
tests/index.spec.js

Ref: https://github.com/ant-design/ant-design/issues/4395

feat: add onNextClick and onPrevClick

---

package.json
src/TabBarMixin.js

Close: https://github.com/ant-design/ant-design/issues/5165
Close: https://github.com/react-component/tabs/issues/60

chore: add warning for missed tab property

---

assets/index/common.less
assets/index/left.less
assets/index/right.less
assets/index/top.less
package.json
src/ScrollableTabBarMixin.js
tests/__snapshots__/index.spec.js.snap

滚动时箭头出现动画和增加 tabs-nav-container 的 padding 平滑动画

出现滚动时切换动画增加

---

src/ScrollableTabBarMixin.js

fix animate end position error

---

src/ScrollableTabBarMixin.js

更新出现滚动时的位移动画。。
1. 以 prev 按钮的动画结束来调用位移动画;
2. nav 的宽度大于 wrap 宽度后拦截了动画， 以 1 为启动动画。

update scroll switch animate

---

src/ScrollableTabBarMixin.js

Improve animate

---

examples/defaultActiveKey.js
package.json
src/ScrollableTabBarMixin.js

close ant-design/ant-design#7210

Better reponsive

---

src/Tabs.js

Ensure child is not null before accessing key.

---

src/InkTabBarMixin.js

close ant-design/ant-design#8678
close ant-design/ant-design#7564
close ant-design/ant-design#8032

Fix missing ink bar in development

---

src/TabBarMixin.js
src/Tabs.js
tests/index.spec.js
tests/swipe.spec.js

https://github.com/ant-design/ant-design/issues/8176

Add MouseEvent as callback's second argument

---

README.md
examples/activeKey.js
package.json
src/ScrollableTabBarMixin.js
src/Tabs.js

Add `navWrapper` props in `Tabs` which mentioned in https://github.com/react-component/tabs/pull/90, this allows DnD feature in tabs.
cc @benjycui

add navwrapper function

---

src/SwipeableTabBarNode.js

fix(SwipeableTabBarNode): totalDelta is missing in didUpdate setCache

---

examples/activeKey.js
src/InkTabBarNode.js
tests/index.spec.js

fix antd [#13029](https://github.com/ant-design/ant-design/issues/13029)

Remove inkbar when key != activeKey

---

examples/antd.js
src/InkTabBarNode.js
src/TabBarTabsNode.js
src/utils.js
tests/index.spec.js

Fix [#12968](https://github.com/ant-design/ant-design/issues/12968)

Let tabBarGutter works when tabBarPosition == 'left' || 'right'

---

package.json
src/Sentinel.jsx
src/TabPane.js
src/Tabs.js
tests/__snapshots__/index.spec.js.snap
tests/__snapshots__/swipe.spec.js.snap
tests/tab.spec.js

* Fix tab shift when new tabPane has element with `autoFocus`
* Fix tab type `TAB` to make the focus out of TabPane
ref: https://github.com/ant-design/ant-design/issues/11748
ref: https://github.com/ant-design/ant-design/issues/11261

Fix tab change logic

---

src/InkTabBarNode.js
src/ScrollableTabBarNode.js
src/utils.js
tests/__snapshots__/index.spec.js.snap
tests/__snapshots__/swipe.spec.js.snap

#157 
1. fix ie9 is not support translate3d
2. fix get a wrong message when npm run lint 
3. update snapshot

fix ie9 is not support translate3d

---

package.json
src/Tabs.js

refactor: Migrate react lifecycle methods

---

examples/antd.js
examples/rtl.js
src/TabBarRootNode.js
src/TabContent.js
src/utils.js
tests/__snapshots__/rtl.spec.js.snap
tests/rtl.spec.js

Fix rtl issues

---

README.md
examples/mix.tsx
src/TabNavList/index.tsx
src/Tabs.tsx
src/hooks/useSyncState.ts
src/interface.ts
tests/overflow.test.tsx

ref https://github.com/ant-design/ant-design/pull/24552

feat: support onTabScroll

---

assets/rtl.less
examples/overflow.tsx
src/TabNavList/OperationNode.tsx

fix: add tabs dropdown rtl classname

---

src/TabNavList/index.tsx

fix https://github.com/ant-design/ant-design/issues/25302

fix: recalculate tabSizes when tabs order  changed

---

examples/extra.tsx
examples/mix.tsx
src/TabNavList/index.tsx
src/Tabs.tsx
src/interface.ts
tests/index.test.tsx

https://github.com/ant-design/ant-design/issues/24522#issue-626162474
| name | type | default | description |
| --- | --- | --- | --- |
| tabBarExtraContent | `React.ReactNode` \| `{left: React.ReactNode, right: React.ReactNode}` |  `-` |

feat: add slot to support extra position

---

package.json
src/TabNavList/OperationNode.tsx
tests/common/util.tsx
tests/overflow.test.tsx

现在 dropdown 过于灵敏了，加上和 antd Dropdown 一样的延迟。
https://github.com/ant-design/ant-design/blob/e09040f3af8d6f1c9b6eb56b8be676c0885ec51d/components/dropdown/dropdown.tsx#L187-L190

feat: add default mouseEnterDelay and mouseLeaveDelay

---

README.md

fix read me file, wrong rows order

fix read me file, wrong rows order

---

README.md

`direction`, `destroyInactiveTabPane` were switched

Fix transposed documentation

---

.gitignore
package.json
src/TabNavList/index.tsx
src/hooks/useRaf.ts

prepare for ant-design/ant-design#27864

chore: remove raf

---

src/TabNavList/index.tsx

Solves issue `Cannot set property 'scrollLeft' of null`

Fix focus on non-existing ref 

---

src/interface.ts

improve renderTabBar props TS definition to help us know exactly what props actually provided.

fix: improve ts definition

---

src/Tabs.tsx
tests/index.test.tsx

close https://github.com/ant-design/ant-design/issues/33032

fix: onChange should not trigger when click current tab

---

src/TabNavList/index.tsx
src/hooks/useVisibleRange.ts
tests/common/util.tsx
tests/overflow.test.tsx

close https://github.com/ant-design/ant-design/issues/34235
﻿

fix: more dropdown should not contain last tab if scrolled

---

src/hooks/useRaf.ts

closes: https://github.com/ant-design/ant-design/issues/35367

fix: be compatible with react 18 StrictMode in dev

---

package.json
src/TabNavList/OperationNode.tsx

ref https://github.com/ant-design/ant-design/pull/35584#issuecomment-1140439339

chore: bump rc-tabs

---

assets/panels.less
docs/demo/animated.md
docs/examples/animated.less
docs/examples/animated.tsx
jest.config.js
package.json
src/TabPanelList/TabPane.tsx
src/TabPanelList/index.tsx
src/Tabs.tsx
src/hooks/useAnimateConfig.ts
src/interface.ts
tests/__snapshots__/index.test.tsx.snap
tests/index.test.tsx
tests/setupFilesAfterEnv.js

https://tabs-git-motion-react-component.vercel.app/demo/animated

refactor: Customize Motion support

---

src/Tabs.tsx

fixes [ant-design/36959](https://github.com/ant-design/ant-design/issues/36959).

chore: remove `mergedTabPosition`

---

package.json

chore: upgrade rc-menu to 9.7.2

---

src/TabNavList/index.tsx
tests/common/util.tsx
tests/index.test.tsx

fix https://github.com/ant-design/ant-design/issues/39190

feat: fix resize

---

src/TabNavList/index.tsx

close https://github.com/ant-design/ant-design/issues/39999

fix: tabs should not get warning when unmounted

---

src/TabNavList/TabNode.tsx
src/TabNavList/index.tsx
src/util.ts
tests/index.test.tsx

close https://github.com/ant-design/ant-design/issues/41129

fix: quote in key should not cause tabs crash

---

src/TabNavList/OperationNode.tsx
src/TabNavList/TabNode.tsx
src/util.ts
tests/index.test.tsx

- If closable is not explicitly set to true, the remove button should be hidden when closeIcon is null or false

refactor: refactor closeIcon

---

.gitignore
docs/demo/indicator.md
docs/examples/indicator.tsx
src/TabNavList/index.tsx
src/Tabs.tsx
src/hooks/useIndicator.ts
tests/common/util.tsx
tests/index.test.tsx

https://github.com/ant-design/ant-design/issues/44311

feat: custom indicator length

---

package.json
src/TabNavList/AddButton.tsx
src/TabNavList/ExtraContent.tsx
src/TabNavList/OperationNode.tsx
src/TabNavList/TabNode.tsx
src/TabNavList/Wrapper.tsx
src/TabNavList/index.tsx
src/TabPanelList/TabPane.tsx
src/TabPanelList/index.tsx
src/Tabs.tsx
src/hooks/useIndicator.ts
src/hooks/useOffsets.ts
src/hooks/useTouchMove.ts
src/index.ts
src/interface.ts
src/util.ts

style: code optimization

---

src/util.ts

we can use PropertyKey instaed of key list

refactor: use PropertyKey instaed of key list

---

src/hooks/useTouchMove.ts

Fixes this: 
https://github.com/ant-design/ant-design/issues/29645

fixing tab bar swipe in cross axis

---

src/hooks/useIndicator.ts
tests/index.test.tsx

https://github.com/ant-design/ant-design/issues/53378
修复 inkStyle 和 activeOffset 抖动的问题。

perf: fix Maximum update depth exceeded caused by inkStyle shaking

---

docs/examples/basic.tsx
src/TabNavList/index.tsx
tests/accessibility.test.tsx

https://github.com/ant-design/ant-design/issues/53691

 fix: Tabs should activate it when press enter/space on unactive tab

---

README.md
docs/examples/mix.tsx
src/TabPanelList/TabPane.tsx
src/TabPanelList/index.tsx
src/Tabs.tsx
tests/index.test.tsx

chore: rename destroyInactiveTabPane => destroyOnHidden

chore: rename destroyInactiveTabPane => destroyOnHidden

---

src/TabNavList/index.tsx
tests/accessibility.test.tsx

chore(a11y): support middle mouse button to close
