react-component/tabs

- src/TabBarMixin.js
- src/TabContent.js
Hello!
I have some use cases, when children of <Tabs> may be null.
For example:
`{ this.state.haveAccessForTab ? <TabPane></TabPane> : null`
Does my changes break anything?
I would be very grateful if these changes go to the upstream.
> Child of <Tab> can be null

- assets/index/bottom.less
- assets/index/left.less
- assets/index/right.less
- assets/index/top.less
- examples/swipeTabBar.html
- examples/swipeTabBar.js
- src/SwipeableTabBar.js
- src/SwipeableTabBarMixin.js
close https://github.com/ant-design/ant-design-mobile/issues/394
ref: `gitlab/react-ui/ant-mobile/issues/404`
> feat: add swipeableTabBar for antd-mobile

- package.json
This works around https://github.com/yarnpkg/yarn/issues/4093
> package.json: don't use wildcard in "files"

- src/Tabs.js
- tests/index.spec.js
close ant-design/ant-design#7093
> Active first tab when children is changed

- src/InkTabBarMixin.js
Fix tab active ink bar is rendered too long, when initialize, usually happend with css-loader
close ant-design/ant-design#7564
close ant-design/ant-design#8000
close ant-design/ant-design#8001
close ant-tool/atool-doc#40
close dvajs/dva#1300
> Fix active bar render bug

- src/InkTabBarMixin.js
Usually happened when using style-loader
close ant-design/ant-design#7564
close ant-design/ant-design#8000
close ant-design/ant-design#8001
close ant-tool/atool-doc#40
close dvajs/dva#1300
---
> Previous PR #104 is buggy and reverted.
> Fix ink bar too long in development

- src/ScrollableTabBarMixin.js
- tests/index.spec.js
This fixes the computation of size for div.ant-tabs-nav
> Use scrollWidth/Height instead of offsetWidth/Height.

- assets/index/bottom.less
- assets/index/common.less
- assets/index/left.less
- assets/index/right.less
- assets/index/top.less
- src/ScrollableTabBarMixin.js
close https://github.com/ant-design/ant-design/issues/9371
change another approach to fix https://github.com/ant-design/ant-design/issues/8861
> Fix tab offset

- src/SwipeableTabBarMixin.js
> Refresh cache after update

- src/SwipeableTabContent.js
#124 Fix the issue that can't not get tabBarPosition and other props
(most of demo are dead)
> fix onPanStart with arrow function

- assets/index/common.less
- src/InkTabBarNode.js
- src/utils.js
简单来说就是上层 dom 存在 `scale(x)` 的时候，内部通过 `getBoundingClientRect` 计算出的 `left` 值不正确。所以用 `getComputedStyle` 自己算了 left / top
ref: https://github.com/ant-design/ant-design/issues/8992
> Use computed style

- package.json
The `rc-hammerjs` package has peer dependencies on `react`, which means that `tabs` also depends on it.
Related: https://github.com/react-component/editor-mention/pull/35
Related: https://github.com/react-component/editor-core/pull/35
> Adds react to the peer dependencies

- package.json
- src/ScrollableTabBarNode.js
This change uses ResizeObserver to detect size change when it's supported, otherwise fallback to the original method of window resize event.
This should fix https://github.com/ant-design/ant-design/issues/15607 for chrome
Implementing a real resize listener for old browser is just too heavy. I think using ResizeObserver to fix chrome first and wait for other browser to adopt this feature is the best option.
> use ResizeObserver to detect size change

- .eslintrc.js
- HISTORY.md
- README.md
- package.json
- src/InkTabBar.js
- src/InkTabBarNode.js
- src/SaveRef.js
- src/ScrollableInkTabBar.js
- src/ScrollableTabBarNode.js
- src/SwipeableTabBarNode.js
- src/SwipeableTabContent.js
- src/TabBarRootNode.js
- src/TabBarSwipeableTabs.js
- src/TabBarTabsNode.js
- src/TabContent.js
- src/TabPane.js
- src/Tabs.js
- tests/__snapshots__/a11y.spec.js.snap
- tests/a11y.spec.js
- close ant-design/ant-design#22264
- close #242
- close #254
- close ant-design/ant-design#9768
- close ant-design/ant-design#15610
- close ant-design/ant-design#7948
> Support keyboard

- src/TabPanelList/TabPane.tsx
- tests/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/ant-design/issues/25343
When `animated` is false, using `display: none` which is much faster than `visibility: hidden`.
> ⚡️ improve Tabs switch performance

- README.md
The `type`,`default` and `description` field were swapped for the `direction` and `destroyInactivetabPane` rows of the Tabs API documentation.
> readme Typo fix direction / destroyInactiveTabPane

- src/TabNavList/index.tsx
- tests/overflow.test.tsx
resolves: https://github.com/ant-design/ant-design/issues/27712
> fix: scroll position should be reset when all tabs are removed

- src/TabNavList/index.tsx
- src/hooks/useTouchMove.ts
移除缓动动画事件阻止效果，在 MAC 下非常容易触发页面跳转。
> refactor: RM opt of preventDefault logic

- docs/examples/basic.tsx
- src/TabNavList/TabNode.tsx
- src/TabNavList/index.tsx
- tests/index.test.tsx
https://github.com/ant-design/ant-design/issues/31462
> fix: tabBarGutter in first tab

- .prettierrc
- src/TabNavList/index.tsx
- src/interface.ts
resolve https://github.com/ant-design/ant-design/issues/32787
> chore: update ts def

- src/TabNavList/OperationNode.tsx
- src/TabNavList/index.tsx
- src/Tabs.tsx
- tests/overflow.test.tsx
Takes over this abandoned PR: https://github.com/react-component/tabs/pull/320 PR: https://github.com/react-component/tabs/pull/486
close #320
close #486
> Adding "getPopupContainer" prop

- docs/examples/overflow.tsx
- src/TabNavList/ExtraContent.tsx
- src/TabNavList/index.tsx
- src/hooks/useVisibleRange.ts
- src/interface.ts
- src/util.ts
- tests/common/util.tsx
- tests/mobile.test.tsx
- tests/overflow.test.tsx
ref https://github.com/ant-design/ant-design/issues/37721
> fix: Tabs position calculation

- package.json
[This PR](https://github.com/react-component/tabs/pull/595) introduced the usage of `useComposeRef` (imported from `rc-util`). However, according to the [changelog](https://github.com/react-component/util/releases/tag/v5.16.0), this function was only introduced in 5.16.0. `rc-tabs` only requires `rc-util@^5.5.0` which is why this module might not work under certain setups.
For example, I get the following warning in webpack (which results in a run time exception when starting my web app):
```
WARNING in ./node_modules/rc-tabs/es/TabNavList/index.js 425:9-22
export 'useComposeRef' (imported as 'useComposeRef') was not found in 'rc-util/es/ref' (possible exports: composeRef, fillRef, supportRef)
1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more …
```
> Fix useComposeRef not found error

- src/TabNavList/index.tsx
fix https://github.com/ant-design/ant-design/issues/39477
https://github.com/react-component/tabs/pull/620/files#diff-375a69ef7e1bc640b62b899390e743d4f0bcaa3e9f95ca2cb8c61bc2a2137627L335
挪到 effect 里的时候，这边漏了。
> fix: resize not trigger

- src/TabNavList/TabNode.tsx
- src/TabNavList/index.tsx
- src/util.ts
- tests/index.test.tsx
- Revert "Revert "fix: quote in key should not cause tabs crash (#655)""
- fix: quotes in key crashes
> fix: quotes in key crashed

- src/hooks/useVisibleRange.ts
这种 DOM size 的 test mock 不出来，比较蛋疼。
fix https://github.com/ant-design/ant-design/issues/42556
> fix: tabs dropdown collapse

- package.json
https://github.com/ant-design/ant-design/pull/43310
> chore: upgrade to rc-menu@ 9.11.0

- docs/demo/dynamic-extra.md
- docs/examples/dynamic-extra.tsx
- src/TabNavList/index.tsx
resolve https://github.com/ant-design/ant-design/issues/44632
resolve https://github.com/ant-design/ant-design/issues/38270
tabBarExtraContent 如果根据 activeKey 显示时，点击 最后一个tab 时失效
https://github.com/react-component/tabs/assets/13554001/06c1dd56-702c-44b1-800f-a74ad44d5e9a
`ant-design`线上`demo`，操作顺序是 **先点击折叠的Tab4,  然后点击Tab5, 继续点击Tab6**
https://codesandbox.io/s/hua-dong-antd-5-4-2-forked-jp2jmf?file=/demo.tsx
或者使用当前库的demo
```tsx
const items: TabsProps['items'] = [];
for (let i = 0; i < 50; i += 1) {
items.push({
key: String(i),
label: `Tab ${i}`,
children: `Content of ${i}`,
});
}
export default () => {
const [key, setKey] = React.useState('0');
const extra = React.useMemo(() => {
if (key === '0') {
return (
<div>额外内容</div>
)
} 
return null
}, [key])
return (
<div style={{ maxWidth: 550 }}> …
```
> fix: 根据activeKey显示额外内容导致最后一个tab点击失效

- README.md
- src/TabPanelList/index.tsx
- tests/index.test.tsx
Fixes https://github.com/ant-design/ant-design/issues/45338
> Fix: apply destroyInactiveTabPane from the TabPane

- src/TabNavList/index.tsx
- tests/common/util.tsx
- tests/overflow.test.tsx
ref:
* https://github.com/ant-design/ant-design/issues/39079
* https://github.com/ant-design/ant-design/issues/44668
* https://github.com/ant-design/ant-design/issues/45231
closes #674 #667
> fix: Offset logic with decimal

- README.md
This PR fixes typos in **README.md** file.
Following typos were fixed:
`resposive` -> `responsive`
No other changes.
> FIx: typo in README.md

- src/TabNavList/TabNode.tsx
- tests/__snapshots__/index.test.tsx.snap
- tests/index.test.tsx
> fix: add span tag to label

- docs/examples/indicator.tsx
- src/TabNavList/index.tsx
- src/Tabs.tsx
- src/hooks/useIndicator.ts
- tests/index.test.tsx
- https://github.com/ant-design/ant-design/issues/46191#issuecomment-1849217334
> refactor: refactor indicator props

- src/TabNavList/OperationNode.tsx
- src/TabNavList/index.tsx
- src/Tabs.tsx
- src/interface.ts
- tests/overflow.test.tsx
ref：https://github.com/ant-design/ant-design/issues/48085
add a new props to control overflow trigger way
In the tabs component, currently we only have hover functionality for triggering the overflow. However, some scenarios require a click action.
> feat: add overflow trigger props

- README.md
| name | type | default | description |
| --- | --- | --- | --- |
| editable | { onEdit(type: 'add' | 'remove', info: { key, event }), showAdd: boolean, removeIcon: ReactNode, addIcon: ReactNode } | - | config tab editable |
| name | type | default | description |
| --- | --- | --- | --- |
| editable | { onEdit(type: 'add' \| 'remove', info: { key, event }), showAdd: boolean, removeIcon: ReactNode, addIcon: ReactNode } | - | config tab editable |
> docs(README): API-Tabs editable column add escape to avoid content to be separated

- src/hooks/useTouchMove.ts
touchstart、touchend 中都没有调用 preventDefault，所以改为 true。
wheel 中有调用 preventDefault，改为 false
> fix: resolve passive warning

- src/TabNavList/index.tsx
- tests/overflow.test.tsx
Some older browsers (e.g. Chrome 45) don't support **x** and **y** properties as part of the `DOMRect` object returned from **getBoundingClientRect**. This is a problem because **getTabSize** returns wrong values which produces visual inconsistencies, so in this MR I'm replacing the **x** with **left** and **y** with **top**.
> fix: get correct values from 'getTabSize' in older browsers

- src/TabNavList/index.tsx
In my case,when I use the `Tabs` component of `antd`, I have found the OperationNode will repeatedly change status between appearing and disappearing when the tabs component's with is almost equal to the sum of the width of all tab items.
Then I found one of the parameters `visibleTabContentValue` of hook function `useVisibleRange` will repeatedly change. I just try to figure it out what happen.
At last, I've found that the `needScroll` value's judgemental condition maybe not correct.(the value of `t+a` is `tabContentSizeValue + addSizeValue`). We can find these two number is almost equal so that they are equal. And then the needScroll is false.
So I think the `needScroll` can be just only comparing the part of integer is enough.
BTW, I just only test my case without other complicated …
> fix: The OperationNode will repeatedly change status between appearing and disappearing.

- src/TabNavList/index.tsx
- tests/accessibility.test.tsx
https://github.com/react-component/tabs/pull/790 for antd 5.x
> fix: Tabs press Enter/Space on active tab should not trigger onChange
